/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgriculturalResource {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'resourceType' : ResourceType,
}
export interface CrisisReport {
  'id' : bigint,
  'resolved' : boolean,
  'description' : string,
  'timestamp' : bigint,
  'contactNumber' : string,
  'crisisType' : CrisisType,
  'location' : string,
  'farmerName' : string,
}
export type CrisisType = { 'suicidalThoughts' : null } |
  { 'emotionalDistress' : null } |
  { 'loanRepaymentStress' : null };
export interface CropStat {
  'region' : string,
  'year' : bigint,
  'cropName' : string,
  'price' : bigint,
  'yield' : bigint,
}
export interface GovernmentScheme {
  'id' : bigint,
  'applicationProcess' : string,
  'contactInfo' : string,
  'name' : string,
  'description' : string,
  'level' : SchemeLevel,
  'eligibility' : string,
}
export interface MarketPrice {
  'unit' : string,
  'marketLocation' : string,
  'price' : bigint,
  'commodity' : string,
}
export type ResourceType = { 'stressManagement' : null } |
  { 'bestPractice' : null } |
  { 'financialLiteracy' : null };
export type SchemeLevel = { 'central' : null } |
  { 'state' : null };
export interface SupportContact {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'organization' : string,
  'phoneNumber' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addAgriculturalResource' : ActorMethod<
    [string, string, ResourceType],
    bigint
  >,
  'addCropStatistic' : ActorMethod<
    [string, bigint, bigint, bigint, string],
    undefined
  >,
  'addGovernmentScheme' : ActorMethod<
    [string, string, string, string, string, SchemeLevel],
    bigint
  >,
  'addMarketPrice' : ActorMethod<[string, bigint, string, string], undefined>,
  'addSupportContact' : ActorMethod<[string, string, string, string], bigint>,
  'getAllAgriculturalResources' : ActorMethod<[], Array<AgriculturalResource>>,
  'getAllCrisisReports' : ActorMethod<[], Array<CrisisReport>>,
  'getAllGovernmentSchemes' : ActorMethod<[], Array<GovernmentScheme>>,
  'getAllMarketPrices' : ActorMethod<[], Array<MarketPrice>>,
  'getAllSupportContacts' : ActorMethod<[], Array<SupportContact>>,
  'getCropStatistics' : ActorMethod<[string], Array<CropStat>>,
  'getCropStatisticsByRegion' : ActorMethod<[string], Array<CropStat>>,
  'getCropStatisticsByYear' : ActorMethod<[bigint], Array<CropStat>>,
  'getMarketPrice' : ActorMethod<[string], MarketPrice>,
  'getResourcesByType' : ActorMethod<
    [ResourceType],
    Array<AgriculturalResource>
  >,
  'getSchemesByLevel' : ActorMethod<[SchemeLevel], Array<GovernmentScheme>>,
  'getUnresolvedCrisisReports' : ActorMethod<[], Array<CrisisReport>>,
  'getWeatherData' : ActorMethod<[string], string>,
  'reportCrisis' : ActorMethod<
    [string, string, string, CrisisType, string, bigint],
    bigint
  >,
  'resolveCrisis' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];