/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResourceType = IDL.Variant({
  'stressManagement' : IDL.Null,
  'bestPractice' : IDL.Null,
  'financialLiteracy' : IDL.Null,
});
export const SchemeLevel = IDL.Variant({
  'central' : IDL.Null,
  'state' : IDL.Null,
});
export const AgriculturalResource = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'resourceType' : ResourceType,
});
export const CrisisType = IDL.Variant({
  'suicidalThoughts' : IDL.Null,
  'emotionalDistress' : IDL.Null,
  'loanRepaymentStress' : IDL.Null,
});
export const CrisisReport = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'contactNumber' : IDL.Text,
  'crisisType' : CrisisType,
  'location' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const GovernmentScheme = IDL.Record({
  'id' : IDL.Nat,
  'applicationProcess' : IDL.Text,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'level' : SchemeLevel,
  'eligibility' : IDL.Text,
});
export const MarketPrice = IDL.Record({
  'unit' : IDL.Text,
  'marketLocation' : IDL.Text,
  'price' : IDL.Nat,
  'commodity' : IDL.Text,
});
export const SupportContact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const CropStat = IDL.Record({
  'region' : IDL.Text,
  'year' : IDL.Nat,
  'cropName' : IDL.Text,
  'price' : IDL.Nat,
  'yield' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAgriculturalResource' : IDL.Func(
      [IDL.Text, IDL.Text, ResourceType],
      [IDL.Nat],
      [],
    ),
  'addCropStatistic' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addGovernmentScheme' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, SchemeLevel],
      [IDL.Nat],
      [],
    ),
  'addMarketPrice' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addSupportContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllAgriculturalResources' : IDL.Func(
      [],
      [IDL.Vec(AgriculturalResource)],
      ['query'],
    ),
  'getAllCrisisReports' : IDL.Func([], [IDL.Vec(CrisisReport)], ['query']),
  'getAllGovernmentSchemes' : IDL.Func(
      [],
      [IDL.Vec(GovernmentScheme)],
      ['query'],
    ),
  'getAllMarketPrices' : IDL.Func([], [IDL.Vec(MarketPrice)], ['query']),
  'getAllSupportContacts' : IDL.Func([], [IDL.Vec(SupportContact)], ['query']),
  'getCropStatistics' : IDL.Func([IDL.Text], [IDL.Vec(CropStat)], ['query']),
  'getCropStatisticsByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CropStat)],
      ['query'],
    ),
  'getCropStatisticsByYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CropStat)],
      ['query'],
    ),
  'getMarketPrice' : IDL.Func([IDL.Text], [MarketPrice], ['query']),
  'getResourcesByType' : IDL.Func(
      [ResourceType],
      [IDL.Vec(AgriculturalResource)],
      ['query'],
    ),
  'getSchemesByLevel' : IDL.Func(
      [SchemeLevel],
      [IDL.Vec(GovernmentScheme)],
      ['query'],
    ),
  'getUnresolvedCrisisReports' : IDL.Func(
      [],
      [IDL.Vec(CrisisReport)],
      ['query'],
    ),
  'getWeatherData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'reportCrisis' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, CrisisType, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'resolveCrisis' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResourceType = IDL.Variant({
    'stressManagement' : IDL.Null,
    'bestPractice' : IDL.Null,
    'financialLiteracy' : IDL.Null,
  });
  const SchemeLevel = IDL.Variant({ 'central' : IDL.Null, 'state' : IDL.Null });
  const AgriculturalResource = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'resourceType' : ResourceType,
  });
  const CrisisType = IDL.Variant({
    'suicidalThoughts' : IDL.Null,
    'emotionalDistress' : IDL.Null,
    'loanRepaymentStress' : IDL.Null,
  });
  const CrisisReport = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'contactNumber' : IDL.Text,
    'crisisType' : CrisisType,
    'location' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const GovernmentScheme = IDL.Record({
    'id' : IDL.Nat,
    'applicationProcess' : IDL.Text,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'level' : SchemeLevel,
    'eligibility' : IDL.Text,
  });
  const MarketPrice = IDL.Record({
    'unit' : IDL.Text,
    'marketLocation' : IDL.Text,
    'price' : IDL.Nat,
    'commodity' : IDL.Text,
  });
  const SupportContact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const CropStat = IDL.Record({
    'region' : IDL.Text,
    'year' : IDL.Nat,
    'cropName' : IDL.Text,
    'price' : IDL.Nat,
    'yield' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAgriculturalResource' : IDL.Func(
        [IDL.Text, IDL.Text, ResourceType],
        [IDL.Nat],
        [],
      ),
    'addCropStatistic' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addGovernmentScheme' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, SchemeLevel],
        [IDL.Nat],
        [],
      ),
    'addMarketPrice' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addSupportContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllAgriculturalResources' : IDL.Func(
        [],
        [IDL.Vec(AgriculturalResource)],
        ['query'],
      ),
    'getAllCrisisReports' : IDL.Func([], [IDL.Vec(CrisisReport)], ['query']),
    'getAllGovernmentSchemes' : IDL.Func(
        [],
        [IDL.Vec(GovernmentScheme)],
        ['query'],
      ),
    'getAllMarketPrices' : IDL.Func([], [IDL.Vec(MarketPrice)], ['query']),
    'getAllSupportContacts' : IDL.Func(
        [],
        [IDL.Vec(SupportContact)],
        ['query'],
      ),
    'getCropStatistics' : IDL.Func([IDL.Text], [IDL.Vec(CropStat)], ['query']),
    'getCropStatisticsByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CropStat)],
        ['query'],
      ),
    'getCropStatisticsByYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CropStat)],
        ['query'],
      ),
    'getMarketPrice' : IDL.Func([IDL.Text], [MarketPrice], ['query']),
    'getResourcesByType' : IDL.Func(
        [ResourceType],
        [IDL.Vec(AgriculturalResource)],
        ['query'],
      ),
    'getSchemesByLevel' : IDL.Func(
        [SchemeLevel],
        [IDL.Vec(GovernmentScheme)],
        ['query'],
      ),
    'getUnresolvedCrisisReports' : IDL.Func(
        [],
        [IDL.Vec(CrisisReport)],
        ['query'],
      ),
    'getWeatherData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'reportCrisis' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, CrisisType, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'resolveCrisis' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };