/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GovernmentScheme {
    id: bigint;
    applicationProcess: string;
    contactInfo: string;
    name: string;
    description: string;
    level: SchemeLevel;
    eligibility: string;
}
export interface AgriculturalResource {
    id: bigint;
    title: string;
    content: string;
    resourceType: ResourceType;
}
export interface CropStat {
    region: string;
    year: bigint;
    cropName: string;
    price: bigint;
    yield: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CrisisReport {
    id: bigint;
    resolved: boolean;
    description: string;
    timestamp: bigint;
    contactNumber: string;
    crisisType: CrisisType;
    location: string;
    farmerName: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MarketPrice {
    unit: string;
    marketLocation: string;
    price: bigint;
    commodity: string;
}
export interface SupportContact {
    id: bigint;
    name: string;
    email: string;
    organization: string;
    phoneNumber: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum CrisisType {
    suicidalThoughts = "suicidalThoughts",
    emotionalDistress = "emotionalDistress",
    loanRepaymentStress = "loanRepaymentStress"
}
export enum ResourceType {
    stressManagement = "stressManagement",
    bestPractice = "bestPractice",
    financialLiteracy = "financialLiteracy"
}
export enum SchemeLevel {
    central = "central",
    state = "state"
}
export interface backendInterface {
    addAgriculturalResource(title: string, content: string, resourceType: ResourceType): Promise<bigint>;
    addCropStatistic(cropName: string, year: bigint, yield: bigint, price: bigint, region: string): Promise<void>;
    addGovernmentScheme(name: string, description: string, eligibility: string, applicationProcess: string, contactInfo: string, level: SchemeLevel): Promise<bigint>;
    addMarketPrice(commodity: string, price: bigint, unit: string, marketLocation: string): Promise<void>;
    addSupportContact(name: string, phoneNumber: string, email: string, organization: string): Promise<bigint>;
    getAllAgriculturalResources(): Promise<Array<AgriculturalResource>>;
    getAllCrisisReports(): Promise<Array<CrisisReport>>;
    getAllGovernmentSchemes(): Promise<Array<GovernmentScheme>>;
    getAllMarketPrices(): Promise<Array<MarketPrice>>;
    getAllSupportContacts(): Promise<Array<SupportContact>>;
    getCropStatistics(cropName: string): Promise<Array<CropStat>>;
    getCropStatisticsByRegion(region: string): Promise<Array<CropStat>>;
    getCropStatisticsByYear(year: bigint): Promise<Array<CropStat>>;
    getMarketPrice(commodity: string): Promise<MarketPrice>;
    getResourcesByType(resourceType: ResourceType): Promise<Array<AgriculturalResource>>;
    getSchemesByLevel(level: SchemeLevel): Promise<Array<GovernmentScheme>>;
    getUnresolvedCrisisReports(): Promise<Array<CrisisReport>>;
    getWeatherData(location: string): Promise<string>;
    reportCrisis(farmerName: string, location: string, contactNumber: string, crisisType: CrisisType, description: string, timestamp: bigint): Promise<bigint>;
    resolveCrisis(reportId: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AgriculturalResource as _AgriculturalResource, CrisisReport as _CrisisReport, CrisisType as _CrisisType, GovernmentScheme as _GovernmentScheme, ResourceType as _ResourceType, SchemeLevel as _SchemeLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAgriculturalResource(arg0: string, arg1: string, arg2: ResourceType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAgriculturalResource(arg0, arg1, to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAgriculturalResource(arg0, arg1, to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addCropStatistic(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCropStatistic(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCropStatistic(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addGovernmentScheme(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: SchemeLevel): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGovernmentScheme(arg0, arg1, arg2, arg3, arg4, to_candid_SchemeLevel_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGovernmentScheme(arg0, arg1, arg2, arg3, arg4, to_candid_SchemeLevel_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addMarketPrice(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarketPrice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarketPrice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSupportContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupportContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupportContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllAgriculturalResources(): Promise<Array<AgriculturalResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgriculturalResources();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgriculturalResources();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCrisisReports(): Promise<Array<CrisisReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCrisisReports();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCrisisReports();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGovernmentSchemes(): Promise<Array<GovernmentScheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGovernmentSchemes();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGovernmentSchemes();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMarketPrices(): Promise<Array<MarketPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketPrices();
            return result;
        }
    }
    async getAllSupportContacts(): Promise<Array<SupportContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupportContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupportContacts();
            return result;
        }
    }
    async getCropStatistics(arg0: string): Promise<Array<CropStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropStatistics(arg0);
            return result;
        }
    }
    async getCropStatisticsByRegion(arg0: string): Promise<Array<CropStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropStatisticsByRegion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropStatisticsByRegion(arg0);
            return result;
        }
    }
    async getCropStatisticsByYear(arg0: bigint): Promise<Array<CropStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropStatisticsByYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropStatisticsByYear(arg0);
            return result;
        }
    }
    async getMarketPrice(arg0: string): Promise<MarketPrice> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketPrice(arg0);
            return result;
        }
    }
    async getResourcesByType(arg0: ResourceType): Promise<Array<AgriculturalResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesByType(to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesByType(to_candid_ResourceType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchemesByLevel(arg0: SchemeLevel): Promise<Array<GovernmentScheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchemesByLevel(to_candid_SchemeLevel_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchemesByLevel(to_candid_SchemeLevel_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnresolvedCrisisReports(): Promise<Array<CrisisReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnresolvedCrisisReports();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnresolvedCrisisReports();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeatherData(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeatherData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeatherData(arg0);
            return result;
        }
    }
    async reportCrisis(arg0: string, arg1: string, arg2: string, arg3: CrisisType, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.reportCrisis(arg0, arg1, arg2, to_candid_CrisisType_n20(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportCrisis(arg0, arg1, arg2, to_candid_CrisisType_n20(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async resolveCrisis(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveCrisis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveCrisis(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AgriculturalResource_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgriculturalResource): AgriculturalResource {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CrisisReport_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CrisisReport): CrisisReport {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CrisisType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CrisisType): CrisisType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GovernmentScheme_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GovernmentScheme): GovernmentScheme {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SchemeLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SchemeLevel): SchemeLevel {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    resolved: boolean;
    description: string;
    timestamp: bigint;
    contactNumber: string;
    crisisType: _CrisisType;
    location: string;
    farmerName: string;
}): {
    id: bigint;
    resolved: boolean;
    description: string;
    timestamp: bigint;
    contactNumber: string;
    crisisType: CrisisType;
    location: string;
    farmerName: string;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        description: value.description,
        timestamp: value.timestamp,
        contactNumber: value.contactNumber,
        crisisType: from_candid_CrisisType_n13(_uploadFile, _downloadFile, value.crisisType),
        location: value.location,
        farmerName: value.farmerName
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    applicationProcess: string;
    contactInfo: string;
    name: string;
    description: string;
    level: _SchemeLevel;
    eligibility: string;
}): {
    id: bigint;
    applicationProcess: string;
    contactInfo: string;
    name: string;
    description: string;
    level: SchemeLevel;
    eligibility: string;
} {
    return {
        id: value.id,
        applicationProcess: value.applicationProcess,
        contactInfo: value.contactInfo,
        name: value.name,
        description: value.description,
        level: from_candid_SchemeLevel_n18(_uploadFile, _downloadFile, value.level),
        eligibility: value.eligibility
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    resourceType: _ResourceType;
}): {
    id: bigint;
    title: string;
    content: string;
    resourceType: ResourceType;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        resourceType: from_candid_ResourceType_n8(_uploadFile, _downloadFile, value.resourceType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suicidalThoughts: null;
} | {
    emotionalDistress: null;
} | {
    loanRepaymentStress: null;
}): CrisisType {
    return "suicidalThoughts" in value ? CrisisType.suicidalThoughts : "emotionalDistress" in value ? CrisisType.emotionalDistress : "loanRepaymentStress" in value ? CrisisType.loanRepaymentStress : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    central: null;
} | {
    state: null;
}): SchemeLevel {
    return "central" in value ? SchemeLevel.central : "state" in value ? SchemeLevel.state : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stressManagement: null;
} | {
    bestPractice: null;
} | {
    financialLiteracy: null;
}): ResourceType {
    return "stressManagement" in value ? ResourceType.stressManagement : "bestPractice" in value ? ResourceType.bestPractice : "financialLiteracy" in value ? ResourceType.financialLiteracy : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CrisisReport>): Array<CrisisReport> {
    return value.map((x)=>from_candid_CrisisReport_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GovernmentScheme>): Array<GovernmentScheme> {
    return value.map((x)=>from_candid_GovernmentScheme_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgriculturalResource>): Array<AgriculturalResource> {
    return value.map((x)=>from_candid_AgriculturalResource_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CrisisType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CrisisType): _CrisisType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): _ResourceType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SchemeLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SchemeLevel): _SchemeLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): {
    stressManagement: null;
} | {
    bestPractice: null;
} | {
    financialLiteracy: null;
} {
    return value == ResourceType.stressManagement ? {
        stressManagement: null
    } : value == ResourceType.bestPractice ? {
        bestPractice: null
    } : value == ResourceType.financialLiteracy ? {
        financialLiteracy: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CrisisType): {
    suicidalThoughts: null;
} | {
    emotionalDistress: null;
} | {
    loanRepaymentStress: null;
} {
    return value == CrisisType.suicidalThoughts ? {
        suicidalThoughts: null
    } : value == CrisisType.emotionalDistress ? {
        emotionalDistress: null
    } : value == CrisisType.loanRepaymentStress ? {
        loanRepaymentStress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SchemeLevel): {
    central: null;
} | {
    state: null;
} {
    return value == SchemeLevel.central ? {
        central: null
    } : value == SchemeLevel.state ? {
        state: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
